### PR TITLE
chore: bump io-uring dependency to 0.5.9

### PR DESCRIPTION
**Pull request by FrankReh**

### CODE REVIEW

**Review by Noah-Kennedy — APPROVED** [review]
What's this for?

**Comment by FrankReh** [comment]
Well, it's to stay current. And it brings in some buffer ring support I got into the crate a long time ago.

**Comment by FrankReh** [comment]
@Noah-Kennedy Please review again. I think because of the merge that was needed, your last approval wasn't enough. Thanks.

**Comment by Noah-Kennedy** [comment]
I think I accidentally enabled the "remove approvals on update" flag. Gonna remove that rq.

**Comment by Noah-Kennedy** [comment]
@FrankReh I removed the flag

**Pull request merged**
