### PR TITLE
Impl fs::remove_file

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Rel: #48 

Suggestions welcome :laughing:

### CODE REVIEW

**Review by Darksonn — APPROVED** [review]
Looks good to me.

**Comment by matthiasbeyer** [comment]
Fixed the formatting and updated the PR.

**Comment by Darksonn** [comment]
This seems to have a conflict with your other PR.

**Comment by matthiasbeyer** [comment]
Do you rebase-merge this or squash-merge?

**Comment by Darksonn** [comment]
It would get squashed.

**Comment by matthiasbeyer** [comment]
Okay, that's sad, because it effectively destroys history and replicability.

**Comment by Darksonn** [comment]
All commits include the id of the PR, so you can view the history on the PR.

**Comment by Darksonn** [comment]
If you want to continue this discussion, feel free to jump on our discord.

**Pull request merged**
