### PR TITLE
write_fixed_all

### PR DESCRIPTION
**Pull request by FrankReh**
Define write_all functions that take fixed buffers.
    
Adds write_fixed_all for TCP and Unix streams.
    
Adds write_fixed_all_at for File.

Also adds an example: tcp_listener_fixed_buffers that uses read_fixed and write_fixed_all.

### CODE REVIEW

**Comment by ollie-etl** [comment]
@FrankReh This should also be applicable to udp and (I think) also the zero copy variants

**Comment by FrankReh** [comment]
@ollie-etl Turns out the UdpSocket can take a write, as it can be connected separately first, so even write_fixed should be defined for the UdpSocket. Just realized that today.

**Comment by FrankReh** [comment]
@ollie-etl Actually, could you clarify what you meant? An *_all* option doesn't seem necessary for UDP sockets as the writes have to be all or nothing anyway.

**Comment by oliverbunting** [comment]
@FrankReh I meant write_fixed, rather than write_fixed_all.

An explosion in number of methods is occurring. I think the case for a builder API overhaul is growing stronger

**Comment by oliverbunting** [comment]
And realised my initial comment was irrelevant. Please disregard

**Review by Noah-Kennedy — APPROVED** [review]

**Pull request merged**
